name: Update Software Versions in Wiki  

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:     

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Generate versions table
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/get_versions.py > versions.md

      - name: Update Yandex Wiki
        run: |
          curl -X PUT \
            -H "Authorization: OAuth ${{ secrets.YANDEX_WIKI_TOKEN }}" \
            -H "Content-Type: text/x-markdown" \
            --data-binary "@versions.md" \
            "https://wiki.yandex-team.ru/api/pages/my_project/versions"